# Generated by Django 6.0.1 on 2026-01-16 16:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('position_actuelle', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('statut', models.CharField(choices=[('EN_LIVRAISON', 'En Livraison'), ('GARAGE', 'Au Garage'), ('PANNE', 'En Panne')], default='GARAGE', max_length=20)),
                ('carburant_niveau', models.FloatField(default=100.0)),
                ('kilometrage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_depart', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('point_arrivee', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('itineraire_prevu', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('date_depart', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vitesse', models.FloatField(default=0.0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
