# Generated by Django 6.0.1 on 2026-01-21 17:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='vehicule',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='position_actuelle',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='HistoriquePosition',
        ),
        migrations.DeleteModel(
            name='Trajet',
        ),
    ]
