# Generated by Django 6.0.1 on 2026-01-21 23:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_trajet_vehicule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='position_actuelle',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('EN_LIVRAISON', 'En Livraison'), ('GARAGE', 'Au Garage'), ('PANNE', 'En Panne'), ('MAINTENANCE_REQUISE', 'Maintenance Requise'), ('PANNE_ESSENCE', 'Panne Essence')], default='GARAGE', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoriquePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vitesse', models.FloatField(default=0.0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_depart', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('point_arrivee', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('itineraire_prevu', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('date_depart', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicule')),
            ],
        ),
    ]
